version: "3.9"
services:
  controller:
    image: ghcr.io/making/fastchat:latest
    pull_policy: always
    entrypoint: [ controller ]
    healthcheck:
      test: perl -mIO::Socket::INET -le 'exit(IO::Socket::INET->new(PeerAddr=>shift,PeerPort=>shift,Proto=>shift,Timeout=>1)?0:1)' 127.0.0.1 21001
    ports:
    - "21001:21001"
  gradio:
    image: ghcr.io/making/fastchat:latest
    pull_policy: always
    depends_on:
      controller:
        condition: service_healthy
    entrypoint: [ gradio ]
    environment:
      CONTROLLER_URL: http://controller:21001
    ports:
    - "7860:7860"
  openai:
    image: ghcr.io/making/fastchat:latest
    pull_policy: always
    depends_on:
      controller:
        condition: service_healthy
    entrypoint: [ openai ]
    environment:
      CONTROLLER_ADDRESS: http://controller:21001
    ports:
    - "8000:8000"