controller: python3 -m fastchat.serve.controller --host 0.0.0.0 --port ${PORT:-21001} ${EXTRA_ARGS}
gradio: python3 -m fastchat.serve.gradio_web_server --host 0.0.0.0 --port ${PORT:-7860} --controller-url ${CONTROLLER_URL} ${EXTRA_ARGS}
openai: python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port ${PORT:-8000} --controller-address ${CONTROLLER_ADDRESS} ${EXTRA_ARGS}
